name: TimesUpPlugin
version: 1.0
main: us.krygowski.spigotplugins.TimesUpPlugin
author: jimkrygowski
commands:
   timesup:
      description: This command allows for the creation of a server shutdown timer
      usage: /timesup set [minutes]
             /timesup cancel
             /timesup pause
             /timesup resume
             /timesup timeleft